// 토스 하루특가 목업. 실제 토스 목록 API 연동 전까지 화면 확인용.
// ponytail: 목업 상수 — API 붙으면 이 파일 삭제하고 GraphQL 쿼리로 교체.

export interface TossDeal {
  id: string;
  productId?: number; // 우리 product 로 등록된 경우의 id (있으면 상세 링크 활성)
  title: string;
  price: number; // 판매가(원)
  discountRate?: number; // 41 => "41% 특가"
  image?: string;
  lowestIn30Days?: boolean; // "30일 최저가"
  delivery?: string; // "내일출발" / "내일도착"
  rating?: number; // 4.7
  reviewCount?: number; // 1933
  bestSeller?: boolean; // "베스트판매자"
  badge?: string; // "역대급특가" 같은 마케팅 라벨
  unitPrice?: string; // "1개당 8,148원"
}

export interface TossSection {
  id: string;
  label: string; // 탭 라벨
  deals: TossDeal[];
}

// 붙여준 토스 원본 그대로. id는 임시(idx).
export const TOSS_SECTIONS: TossSection[] = [
  {
    id: 'daily',
    label: '하루특가',
    deals: [
      {
        id: 'd1',
        productId: 25695675,
        title: 'BYC 보디 드라이 에어 남성 런닝 ODS0005, 블랙, M, 1개',
        price: 7900,
        discountRate: 41,
        lowestIn30Days: true,
        delivery: '내일출발',
      },
      {
        id: 'd2',
        productId: 25672607,
        title: '서재걸 셀업 리포좀 글루타치온, 550mg, 60정, 1개',
        price: 19710,
        discountRate: 60,
        lowestIn30Days: true,
        delivery: '내일출발',
      },
      {
        id: 'd3',
        title: '센토 프라임 고불소 구취케어 치약 아쿠아민트향, 120g, 4개',
        price: 9900,
        discountRate: 53,
        lowestIn30Days: true,
        rating: 4.7,
        reviewCount: 1933,
        delivery: '내일출발',
        bestSeller: true,
      },
      {
        id: 'd4',
        title: '이지드롭 변기크리너, 블루 핸들 1개 + 아쿠아 1팩(12개입), 1세트',
        price: 9900,
        discountRate: 46,
        lowestIn30Days: true,
        delivery: '내일출발',
      },
      {
        id: 'd5',
        title: '코리아나 더블랙 프리미어 기초 3종세트, 토너 + 에멀션 + 크림, 1개',
        price: 19900,
        discountRate: 81,
        lowestIn30Days: true,
        rating: 4.6,
        reviewCount: 74,
        delivery: '내일출발',
      },
      {
        id: 'd6',
        title: '슈리오 펀칭 벨크로 푹신한 웨지 샌들, 브라운, 245mm',
        price: 22400,
        discountRate: 56,
        lowestIn30Days: true,
        rating: 4.7,
        reviewCount: 15,
        bestSeller: true,
      },
      {
        id: 'd7',
        title: '예스플러스 반팔 면티, 3매, 화이트, M',
        price: 12900,
        discountRate: 55,
        lowestIn30Days: true,
        rating: 4.4,
        reviewCount: 24,
      },
      {
        id: 'd8',
        title: '미가푸드 수제두부 두부과자, 110g, 5개',
        price: 7900,
        discountRate: 53,
        lowestIn30Days: true,
        rating: 4.7,
        reviewCount: 2142,
        bestSeller: true,
      },
      {
        id: 'd9',
        title: '주리에떼 벨라 돌핀 목걸이, 옐로우, 순금 24K 펜던트, 1개 + 14K 체인, 1개',
        price: 258800,
        discountRate: 58,
        lowestIn30Days: true,
        delivery: '내일출발',
      },
    ],
  },
  {
    id: 'best',
    label: '지금 많이 팔리는 BEST',
    deals: [
      {
        id: 'b1',
        title: '삼육김 들기름으로 구운 광천김 도시락김, 4g, 32봉',
        price: 4900,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일출발',
        rating: 4.8,
        reviewCount: 1628,
        bestSeller: true,
      },
      {
        id: 'b2',
        title: '스파클 생수, 무라벨, 500ml, 80개',
        price: 7840,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일출발',
        rating: 4.9,
        reviewCount: 2943,
        bestSeller: true,
      },
      {
        id: 'b3',
        title: '맘스럽 아토워시 프렌치 라벤더 캡슐세제 파우치형, 8g, 200개입',
        price: 5700,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일출발',
        rating: 4.7,
        reviewCount: 969,
        bestSeller: true,
      },
      {
        id: 'b4',
        title: '일양약품 눈건강 루테인 골드, 500mg, 30캡슐, 6박스',
        price: 10800,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일출발',
        rating: 4.7,
        reviewCount: 2229,
        bestSeller: true,
      },
      {
        id: 'b5',
        title: '셰프초이스 한입 치즈 너비아니, 700g, 1개',
        price: 4200,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일도착',
        rating: 4.8,
        reviewCount: 16247,
        bestSeller: true,
      },
      {
        id: 'b6',
        title: '에뛰드 베이킹 파우더 모공 클렌징폼, 160g, 1개',
        price: 3000,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일출발',
        rating: 4.8,
        reviewCount: 2950,
        bestSeller: true,
      },
      {
        id: 'b7',
        title: '랜선식당 연탄불고기, 250g, 4개',
        price: 8300,
        badge: '역대급특가',
        lowestIn30Days: true,
        rating: 4.7,
        reviewCount: 11188,
        bestSeller: true,
      },
      {
        id: 'b8',
        title: '유한메디카 징코 플러스엔탑 혈행 기억력 케어, 60정, 1개',
        price: 4500,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일출발',
        rating: 4.7,
        reviewCount: 5589,
        bestSeller: true,
      },
      {
        id: 'b9',
        title: '일화 초정 탄산수 플레인, 250ml, 30개',
        price: 6900,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일도착',
        rating: 4.7,
        reviewCount: 3268,
        bestSeller: true,
      },
      {
        id: 'b10',
        title: '듀오덤 밴드, 혼합형, 8매입, 1개',
        price: 3800,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일출발',
        rating: 4.8,
        reviewCount: 7701,
        bestSeller: true,
      },
    ],
  },
  {
    id: 'rising',
    label: '인기 급상승',
    deals: [
      {
        id: 'r1',
        title: '한예지 네이처 소프트 롤 화장지, 3겹, 27m, 30롤, 2팩',
        price: 21500,
        discountRate: 30,
        unitPrice: '1롤당 359원',
        rating: 4.3,
        reviewCount: 61,
        bestSeller: true,
      },
      {
        id: 'r2',
        title: '프로스펙스 액티브 슬개골 보호대, 블랙, 2개',
        price: 16296,
        discountRate: 59,
        unitPrice: '1개당 8,148원',
        delivery: '내일출발',
        rating: 4.6,
        reviewCount: 519,
        bestSeller: true,
      },
      {
        id: 'r3',
        title: '3피스 우주인 잠옷 세트, 원컬러, FREE, 1개',
        price: 8850,
        discountRate: 73,
        delivery: '내일출발',
        rating: 4.1,
        reviewCount: 394,
        bestSeller: true,
      },
      {
        id: 'r4',
        title: '제스타 향기나는 습기제거제, 라벤더향, 250g, 18개입, 1개',
        price: 14900,
        discountRate: 35,
        delivery: '내일출발',
        rating: 4.7,
        reviewCount: 593,
        bestSeller: true,
      },
      {
        id: 'r5',
        title: '작심밀도 지리산 사양벌꿀, 2.4kg, 1개',
        price: 50200,
        unitPrice: '100g당 2,092원',
        delivery: '내일출발',
        rating: 4.6,
        reviewCount: 663,
      },
    ],
  },
  {
    id: 'category',
    label: '카테고리 인기',
    deals: [
      {
        id: 'c1',
        title: '킨도 프리미엄 기저귀, 오 슬림 썸머 팬티, 6단계, 120매',
        price: 63700,
        discountRate: 30,
        unitPrice: '1매당 531원',
        rating: 5,
        reviewCount: 3,
        bestSeller: true,
      },
      {
        id: 'c2',
        title: '하기스 보송보송 팬티형, 5단계, 46매x2팩, 92매',
        price: 36720,
        lowestIn30Days: true,
        unitPrice: '1매당 400원',
        delivery: '내일출발',
        rating: 4.9,
        reviewCount: 13,
      },
      {
        id: 'c3',
        title: '페넬로페 씬씬씬 아이스 썸머 팬티 기저귀, 점보형(2XL), 4팩',
        price: 45900,
        discountRate: 24,
        delivery: '내일출발',
        rating: 4.8,
        reviewCount: 6,
        bestSeller: true,
      },
      {
        id: 'c4',
        title: '킨도 프리미엄 기저귀 오 슬림 에어쿨쿨, 4단계, 144매',
        price: 65800,
        discountRate: 30,
        unitPrice: '1매당 457원',
        delivery: '내일출발',
        rating: 5,
        reviewCount: 1,
        bestSeller: true,
      },
      {
        id: 'c5',
        title: '킨도 프리미엄 기저귀 오 슬림 에어 팬츠, 7단계, 104매',
        price: 62300,
        discountRate: 30,
        unitPrice: '1매당 600원',
        rating: 5,
        reviewCount: 3,
        bestSeller: true,
      },
    ],
  },
  {
    id: 'creator',
    label: '크리에이터 PICK',
    deals: [
      {
        id: 'cr1',
        title: '바이마르 솥뚜껑 세라믹 가마솥, 블랙, 1개, 최대커버사이즈 16cm',
        price: 9900,
        discountRate: 90,
        lowestIn30Days: true,
        delivery: '내일출발',
        rating: 4.6,
        reviewCount: 293,
        bestSeller: true,
      },
      {
        id: 'cr2',
        title: '연세두유 무가당 고칼슘 두유 오리지널, 190ml, 48개',
        price: 17900,
        discountRate: 70,
        lowestIn30Days: true,
        unitPrice: '100ml당 197원',
        delivery: '내일출발',
        rating: 4.9,
        reviewCount: 21,
        bestSeller: true,
      },
      {
        id: 'cr3',
        title: '가쯔 쿡스 전자레인지 찜기 라면용기 특대, 다크그레이, 1L, 2개',
        price: 5900,
        discountRate: 62,
        unitPrice: '1개당 2,950원',
        delivery: '내일출발',
        rating: 4.5,
        reviewCount: 766,
        bestSeller: true,
      },
      {
        id: 'cr4',
        title: '몽땅 아낌없는 양배추즙, 100ml, 60포',
        price: 15900,
        discountRate: 55,
        unitPrice: '1포당 265원',
        rating: 4.8,
        reviewCount: 15,
      },
      {
        id: 'cr5',
        title: '윔지스 버라이어티팩, 칫솔+스틱+악어, S, 840g, 1개',
        price: 18500,
        badge: '역대급특가',
        lowestIn30Days: true,
        delivery: '내일도착',
        rating: 4.8,
        reviewCount: 701,
        bestSeller: true,
      },
    ],
  },
  {
    id: 'lowest',
    label: '최저가만 모았어요',
    deals: [
      {
        id: 'l1',
        title: '프리미엄 엠머 파로 효소, 3g, 14포, 4box',
        price: 10900,
        discountRate: 92,
        lowestIn30Days: true,
        delivery: '내일출발',
        rating: 5,
        reviewCount: 4,
        bestSeller: true,
      },
      {
        id: 'l2',
        title:
          '프라카 도자기 다용도볼, 로즈가든 1개 + 옐로우로즈 1개 + 피오니아 1개 + 블루네라 1개, 4개',
        price: 17900,
        discountRate: 62,
        rating: 4.5,
        reviewCount: 60,
      },
      {
        id: 'l3',
        title: '못난이 사과, 10kg, 1개',
        price: 13900,
        discountRate: 57,
        rating: 3.8,
        reviewCount: 243,
        bestSeller: true,
      },
      {
        id: 'l4',
        title: '신선한아침 강원도 햇감자 수미감자, 중, 3kg, 1개',
        price: 5900,
        discountRate: 52,
        lowestIn30Days: true,
      },
    ],
  },
  {
    id: 'conversion',
    label: '구매 전환율 높아요',
    deals: [
      {
        id: 'cv1',
        title: '홍주부 수제 두바이 쫀득 쿠키, 45g, 20개',
        price: 36900,
        discountRate: 26,
        unitPrice: '100g당 4,100원',
        rating: 4.8,
        reviewCount: 98,
        bestSeller: true,
      },
      {
        id: 'cv2',
        title: '가쯔 쿡스 전자레인지 찜기, 라이트그레이, 1L, 2개',
        price: 5900,
        discountRate: 62,
        unitPrice: '1개당 2,950원',
        delivery: '내일출발',
        rating: 4.4,
        reviewCount: 500,
        bestSeller: true,
      },
      {
        id: 'cv3',
        title: '웅진식품 하늘보리 무라벨 에코, 500ml, 20개',
        price: 12400,
        discountRate: 34,
        lowestIn30Days: true,
        unitPrice: '100ml당 124원',
        rating: 4.8,
        reviewCount: 500,
        bestSeller: true,
      },
      {
        id: 'cv4',
        title: '가쯔 쿡스 전자레인지 찜기 라면용기 특대, 다크그레이, 1L, 2개',
        price: 5900,
        discountRate: 62,
        unitPrice: '1개당 2,950원',
        delivery: '내일출발',
        rating: 4.5,
        reviewCount: 766,
        bestSeller: true,
      },
      {
        id: 'cv5',
        title: '에그마을 난각번호 1번 유정란, 20구, 2판',
        price: 21680,
        discountRate: 22,
        unitPrice: '1개당 10,840원',
        delivery: '내일출발',
        rating: 4.8,
        reviewCount: 1409,
      },
    ],
  },
];
