services:
  jirum-alarm-landing-development:
    build:
      context: ../../../../
      dockerfile: apps/landing/deploy/development/Dockerfile
    image: jirum-alarm-landing-development
    ports:
      - "3001:3000"
