import StyleDictionary from 'style-dictionary';

/**
 * 지름알림 디자인 토큰 빌드 (SSOT → 각 플랫폼 생성물)
 *
 * 정답 기준: Figma = web 값. primitive/*.json 한 곳에만 hex/스케일이 존재하고,
 * 여기서 web(Tailwind v4 @theme)·mobile/admin(Tailwind config)·TS 상수를 생성한다.
 *
 * ⚠️ web 무손실 전환 원칙:
 *   현 단계 생성물(web.css)은 apps/web globals.css의 @theme 중 "토큰이 소유하는" 값만
 *   재현한다(색/타이포 스케일 오버라이드/shadow/breakpoint/container). env() 기반 spacing,
 *   --font-sans(= var(--font-pretendard)), --breakpoint-mobile-max 등 앱 런타임 값은
 *   앱 globals.css에 그대로 남긴다. 그래서 시각 변화 0.
 *   typography 18종·hotdeal-graph는 토큰엔 있지만 아직 방출 안 함(컴포넌트 단계용).
 */

// kebab 유지하며 그룹 prefix만 떼는 헬퍼 (color.primary.500 -> primary-500)
const stripGroup = (token, group) => token.path.slice(token.path[0] === group ? 1 : 0).join('-');

// --- Tailwind v4 @theme CSS (web) ---
StyleDictionary.registerFormat({
  name: 'jirum/tailwind-v4-theme',
  format: ({ dictionary }) => {
    const byType = (type) => dictionary.allTokens.filter((t) => t.$type === type || t.type === type);

    const lines = [];
    lines.push('/* AUTO-GENERATED by @jirum/design-tokens — DO NOT EDIT BY HAND. */');
    lines.push('/* SSOT: packages/design-tokens/tokens/primitive/*.json (Figma=web 값) */');
    lines.push('');
    lines.push('@theme {');

    // breakpoints
    lines.push('  /* breakpoints */');
    for (const t of byType('dimension').filter((t) => t.path[0] === 'breakpoint')) {
      lines.push(`  --breakpoint-${t.path.slice(1).join('-')}: ${t.$value};`);
    }
    lines.push('');

    // container
    lines.push('  /* container */');
    for (const t of byType('dimension').filter((t) => t.path[0] === 'container')) {
      lines.push(`  --container-${t.path.slice(1).join('-')}: ${t.$value};`);
    }
    lines.push('');

    // font size / leading overrides
    lines.push('  /* font size (overrides) */');
    for (const t of byType('dimension').filter((t) => t.path[0] === 'text')) {
      lines.push(`  --text-${t.path.slice(1).join('-')}: ${t.$value};`);
    }
    for (const t of byType('dimension').filter((t) => t.path[0] === 'leading')) {
      lines.push(`  --leading-${t.path.slice(1).join('-')}: ${t.$value};`);
    }
    lines.push('');

    // colors — apps/web globals.css 순서(error→primary→gray→secondary)에 맞춰 무손실 diff 보장.
    // white/black/link는 색 블록 맨 위 (현 globals.css와 동일 배치).
    lines.push('  /* colors */');
    const colorGroupOrder = ['error', 'primary', 'gray', 'secondary'];
    const singles = byType('color').filter((t) => t.path.length === 2);
    for (const name of ['white', 'black', 'link']) {
      const t = singles.find((t) => t.path[1] === name);
      if (t) lines.push(`  --color-${name}: ${t.$value};`);
    }
    for (const group of colorGroupOrder) {
      for (const t of byType('color').filter((t) => t.path[1] === group && t.path[0] === 'color')) {
        lines.push(`  --color-${stripGroup(t, 'color')}: ${t.$value};`);
      }
    }
    // hotdeal-graph는 현 단계 방출 제외 (컴포넌트 단계용) — 위 그룹 목록에 미포함이라 자동 제외됨.
    lines.push('');

    // shadow — css transformGroup이 객체를 평탄화하므로 원본값(token.original.$value)에서 조립.
    lines.push('  /* shadow */');
    for (const t of byType('shadow')) {
      const v = t.original?.$value ?? t.$value;
      const css = `${v.offsetX} ${v.offsetY} ${v.blur} ${v.spread} ${v.color}`;
      lines.push(`  --shadow-${t.path.slice(1).join('-')}: ${css};`);
    }

    lines.push('}');
    lines.push('');
    return lines.join('\n');
  },
});

// --- Tailwind config tokens (mobile / admin) : theme.extend 조각 (CJS) ---
StyleDictionary.registerFormat({
  name: 'jirum/tailwind-config-tokens',
  format: ({ dictionary }) => {
    const colors = {};
    for (const t of dictionary.allTokens.filter((t) => (t.$type || t.type) === 'color')) {
      const [, group, shade] = t.path; // color.<group>.<shade> | color.<single>
      if (t.path.length === 2) {
        colors[t.path[1]] = t.$value;
      } else {
        colors[group] = colors[group] || {};
        colors[group][shade] = t.$value;
      }
    }
    return (
      '// AUTO-GENERATED by @jirum/design-tokens — DO NOT EDIT BY HAND.\n' +
      '// SSOT: packages/design-tokens/tokens/primitive/*.json (Figma=web 값)\n' +
      'module.exports = {\n  colors: ' +
      JSON.stringify(colors, null, 2).replace(/\n/g, '\n  ') +
      ',\n};\n'
    );
  },
});

const PRIMITIVE = 'tokens/primitive/**/*.json';

export default {
  source: [PRIMITIVE],
  log: { verbosity: 'verbose' },
  platforms: {
    web: {
      transformGroup: 'css',
      buildPath: 'build/',
      files: [{ destination: 'web.css', format: 'jirum/tailwind-v4-theme' }],
    },
    tailwind: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [{ destination: 'tailwind.tokens.cjs', format: 'jirum/tailwind-config-tokens' }],
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [
        { destination: 'tokens.js', format: 'javascript/es6' },
        { destination: 'tokens.d.ts', format: 'typescript/es6-declarations' },
      ],
    },
  },
};
