import StyleDictionary from 'style-dictionary';

/**
 * 지름알림 디자인 토큰 빌드 (SSOT → 각 플랫폼 생성물)
 *
 * 정답 기준: Figma = web 값. primitive/*.json 한 곳에만 hex/스케일이 존재하고,
 * 여기서 web(Tailwind v4 @theme)·mobile/admin(Tailwind config)·TS 상수를 생성한다.
 *
 * ⚠️ web 무손실 전환 원칙:
 *   현 단계 생성물(web.css)은 apps/web globals.css의 @theme 중 "토큰이 소유하는" 값만
 *   재현한다(색/타이포 스케일 오버라이드/shadow/breakpoint/container). env() 기반 spacing,
 *   --font-sans(= var(--font-pretendard)), --breakpoint-mobile-max 등 앱 런타임 값은
 *   앱 globals.css에 그대로 남긴다. 그래서 시각 변화 0.
 *   typography 14종은 web.css(@utility)·tailwind.tokens.cjs(fontSize)로 방출하되 아직 소비처가
 *   없어 시각 변화 0. hotdeal-graph는 토큰엔 있지만 아직 방출 안 함(컴포넌트 단계용).
 */

// kebab 유지하며 그룹 prefix만 떼는 헬퍼 (color.primary.500 -> primary-500)
const stripGroup = (token, group) => token.path.slice(token.path[0] === group ? 1 : 0).join('-');

// typography 토큰의 size/leading/weight를 transformGroup 무관하게 뽑아낸다.
// css transformGroup은 $value를 shorthand 문자열("600 28px/38px Pretendard")로 평탄화하고,
// js는 객체로 둔다. original.$value(미해석 참조)에서 size/leading을 직접 읽고, fontWeight 참조는
// dictionary의 font.weight 토큰으로 직접 resolve한다 ({font.weight.semibold} -> 600).
const resolveTypography = (token, allTokens) => {
  const orig = token.original?.$value ?? {};
  const weightTokens = allTokens.filter((t) => t.path[0] === 'font' && t.path[1] === 'weight');
  const wRef = String(orig.fontWeight ?? '');
  const wName = wRef.replace(/^\{font\.weight\.(.+)\}$/, '$1');
  const weightTok = weightTokens.find((t) => t.path[2] === wName);
  const fontWeight = weightTok ? weightTok.$value : orig.fontWeight;
  return { fontSize: orig.fontSize, lineHeight: orig.lineHeight, fontWeight };
};

// --- Tailwind v4 @theme CSS (web) ---
StyleDictionary.registerFormat({
  name: 'jirum/tailwind-v4-theme',
  format: ({ dictionary }) => {
    const byType = (type) => dictionary.allTokens.filter((t) => t.$type === type || t.type === type);

    const lines = [];
    lines.push('/* AUTO-GENERATED by @jirum/design-tokens — DO NOT EDIT BY HAND. */');
    lines.push('/* SSOT: packages/design-tokens/tokens/primitive/*.json (Figma=web 값) */');
    lines.push('');
    lines.push('@theme {');

    // breakpoints
    lines.push('  /* breakpoints */');
    for (const t of byType('dimension').filter((t) => t.path[0] === 'breakpoint')) {
      lines.push(`  --breakpoint-${t.path.slice(1).join('-')}: ${t.$value};`);
    }
    lines.push('');

    // container
    lines.push('  /* container */');
    for (const t of byType('dimension').filter((t) => t.path[0] === 'container')) {
      lines.push(`  --container-${t.path.slice(1).join('-')}: ${t.$value};`);
    }
    lines.push('');

    // font size / leading overrides
    lines.push('  /* font size (overrides) */');
    for (const t of byType('dimension').filter((t) => t.path[0] === 'text')) {
      lines.push(`  --text-${t.path.slice(1).join('-')}: ${t.$value};`);
    }
    for (const t of byType('dimension').filter((t) => t.path[0] === 'leading')) {
      lines.push(`  --leading-${t.path.slice(1).join('-')}: ${t.$value};`);
    }
    lines.push('');

    // colors — apps/web globals.css 순서(error→primary→gray→secondary)에 맞춰 무손실 diff 보장.
    // white/black/link는 색 블록 맨 위 (현 globals.css와 동일 배치).
    lines.push('  /* colors */');
    const colorGroupOrder = ['error', 'primary', 'gray', 'secondary'];
    const singles = byType('color').filter((t) => t.path.length === 2);
    for (const name of ['white', 'black', 'link']) {
      const t = singles.find((t) => t.path[1] === name);
      if (t) lines.push(`  --color-${name}: ${t.$value};`);
    }
    for (const group of colorGroupOrder) {
      for (const t of byType('color').filter((t) => t.path[1] === group && t.path[0] === 'color')) {
        lines.push(`  --color-${stripGroup(t, 'color')}: ${t.$value};`);
      }
    }
    // hotdeal-graph는 현 단계 방출 제외 (컴포넌트 단계용) — 위 그룹 목록에 미포함이라 자동 제외됨.
    lines.push('');

    // shadow — css transformGroup이 객체를 평탄화하므로 원본값(token.original.$value)에서 조립.
    lines.push('  /* shadow */');
    for (const t of byType('shadow')) {
      const v = t.original?.$value ?? t.$value;
      const css = `${v.offsetX} ${v.offsetY} ${v.blur} ${v.spread} ${v.color}`;
      lines.push(`  --shadow-${t.path.slice(1).join('-')}: ${css};`);
    }

    lines.push('}');
    lines.push('');

    // typography 18종 — @utility 클래스로 방출 (fontSize+lineHeight+fontWeight 묶음).
    // 컴포넌트에서 `typography-headline-28sb` 한 클래스로 소비. weight까지 담는다.
    // fontFamily는 앱 런타임 값(var(--font-sans) = var(--font-pretendard))을 쓴다 — 토큰 리터럴
    // 'Pretendard' 대신 web globals.css가 소유한 --font-sans를 참조해 무손실 유지.
    lines.push('/* typography (Figma 스펙) — class 하나로 size/leading/weight 묶음 */');
    for (const t of byType('typography')) {
      const v = resolveTypography(t, dictionary.allTokens);
      lines.push(`@utility typography-${t.path.slice(1).join('-')} {`);
      lines.push('  font-family: var(--font-sans);');
      lines.push(`  font-size: ${v.fontSize};`);
      lines.push(`  line-height: ${v.lineHeight};`);
      lines.push(`  font-weight: ${v.fontWeight};`);
      lines.push('}');
    }
    lines.push('');
    return lines.join('\n');
  },
});

// --- Tailwind config tokens (mobile / admin) : theme.extend 조각 (CJS) ---
StyleDictionary.registerFormat({
  name: 'jirum/tailwind-config-tokens',
  format: ({ dictionary }) => {
    const colors = {};
    for (const t of dictionary.allTokens.filter((t) => (t.$type || t.type) === 'color')) {
      const [, group, shade] = t.path; // color.<group>.<shade> | color.<single>
      if (t.path.length === 2) {
        colors[t.path[1]] = t.$value;
      } else {
        colors[group] = colors[group] || {};
        colors[group][shade] = t.$value;
      }
    }
    // typography 18종 — Tailwind v3 fontSize 맵: ['<size>', { lineHeight, fontWeight }]
    // mobile(NativeWind)/admin이 theme.extend.fontSize에 펼쳐 `text-headline-28sb`로 소비.
    const fontSize = {};
    for (const t of dictionary.allTokens.filter((t) => (t.$type || t.type) === 'typography')) {
      const v = resolveTypography(t, dictionary.allTokens);
      fontSize[t.path.slice(1).join('-')] = [
        v.fontSize,
        { lineHeight: v.lineHeight, fontWeight: String(v.fontWeight) },
      ];
    }

    return (
      '// AUTO-GENERATED by @jirum/design-tokens — DO NOT EDIT BY HAND.\n' +
      '// SSOT: packages/design-tokens/tokens/primitive/*.json (Figma=web 값)\n' +
      'module.exports = {\n  colors: ' +
      JSON.stringify(colors, null, 2).replace(/\n/g, '\n  ') +
      ',\n  fontSize: ' +
      JSON.stringify(fontSize, null, 2).replace(/\n/g, '\n  ') +
      ',\n};\n'
    );
  },
});

const PRIMITIVE = 'tokens/primitive/**/*.json';

export default {
  source: [PRIMITIVE],
  log: { verbosity: 'verbose' },
  platforms: {
    web: {
      transformGroup: 'css',
      buildPath: 'build/',
      files: [{ destination: 'web.css', format: 'jirum/tailwind-v4-theme' }],
    },
    tailwind: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [{ destination: 'tailwind.tokens.cjs', format: 'jirum/tailwind-config-tokens' }],
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [
        { destination: 'tokens.js', format: 'javascript/es6' },
        { destination: 'tokens.d.ts', format: 'typescript/es6-declarations' },
      ],
    },
  },
};
